import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-7xl mx-auto my-5 px-10 flex flex-col">
          <header>
            <h1 className="text-3xl mb-2.5">
              How To Next.js Middleware + TypeScript
            </h1>
          </header>
          <div className="flex-auto">{children}</div>
          <div className="text-center">
            &copy;{' '}
            <a
              href="https://twitter.com/nagasawaaaa"
              className="underline hover:no-underline"
              target="_blank"
              rel="noreferrer nofollow"
            >
              nagasawaaaa
            </a>
          </div>
        </div>
      </body>
    </html>
  );
}
